#!/usr/bin/env php -q
<?php

// Number of spaces to replace tabs with.
$spaces = 4;

// Custom space count.
if (isset($argv[1])) {
	$spaces = intval($argv[1]);
}

echo str_replace("\t", str_repeat(" ", $spaces), 
				 file_get_contents("php://stdin"));
